version: "3"

networks:
  app:
    driver: bridge

services:
  php-fpm:
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
    networks:
      - app
    volumes:
      - .:/src/app
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    depends_on:
      - php-fpm
    networks:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./public:/src/app/public
